# Generated by Django 5.1.3 on 2024-11-22 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='eventos',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 11, 22, 15, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='local',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventos',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='midia/'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='price',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
