# Generated by Django 5.1.3 on 2024-11-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventos_date_creation_eventos_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='description',
            field=models.CharField(default=1.0, max_length=1000),
            preserve_default=False,
        ),
    ]
