# Generated by Django 5.1.3 on 2024-11-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
